### ISSUE TITLE
Cause of death

### ISSUE THREAD

**Issue by rward3182** [rward3182/Myanmar#7]
[UNOPS_SmartVA_Myanmar_v2.xlsx](https://github.com/rward3182/Myanmar/files/1405857/UNOPS_SmartVA_Myanmar_v2.xlsx)
From Sonja:
This form was done for a (separate) mortality survey in Myanmar. They wanted the change so that it just had ‘Cause of death’ rather than all of the different categories of causes (see rows 323 and 521). So you can see how this was achieved here if need be.

**Comment by sonjafirth** [comment]
Remember I said it was actually 512 not 521!!

**Comment by rward3182** [comment]
OK. Sonja noted. Glad you are using it. Rog :)

**Comment by rward3182** [comment]
Taken out multiple causes for both adults and children. Now just has cause of death marked up in grey.
Row 562 child. Adult 359. Initial testing passed

**Comment by rward3182** [comment]
Version with death edits. Taken out Bryan's note
[SmartVA_Myanmar_v16rw105.xlsx](https://github.com/rward3182/Myanmar/files/1420840/SmartVA_Myanmar_v16rw105.xlsx)

**Comment by sonjafirth** [comment]
Hi Roger. Review of current version has raised two issues:

1) Inserting location fields for the cascade have stuffed up the image files (which are no longer against the correct answers - head too big, head too small etc.). Easily fixed but need to be careful about inserting text here - need to insert rows and paste rather than move current entries down. Also probably best to have location fields at the end of the menu - since this list is likely to grow in future. 
2) in the child and neonatal module we are missing two questions about death certificates  (child_5_10 and child_5_11 below). They relate to the UNOPs mortality survey rows 509-512. We need all three questions here in the form. At the moment we just have child_5_12
child_5_10	Was a death certificate issued?
child_5_11	Can I see the death certificate? 
child_5_12	Cause of death

Otherwise everything seems to be working as I would expect and also processing through the SmartVA Analyze.  I was going to try to make these changes but my converter does not seem to work with the new syntax so I cannot check what I have done. Probably best for you to do this and then I can check it? 

Anyway - can talk early next week on this?

**Comment by rward3182** [comment]
Closing as splitting into separate issues.
